# Generated by Django 4.0.4 on 2022-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('shortText', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
